"""PA#8 - DLP-based collision-resistant hash."""

from .dlp_hash import (
    DLPHash,
    DLPHashParams,
    FULL_PARAMS,
    TOY_PARAMS,
    birthday_collision_demo,
    bytes_to_int,
    bytes_to_zq,
    compress_bytes,
    compress_pair,
    compression_collision_reduction_demo,
    find_subgroup_generator,
    generate_safe_prime_subgroup,
    hash_bytes,
    hash_hex,
    hash_truncated,
    int_to_bytes,
    mod_exp,
    mod_inv,
    random_zq,
    recover_alpha_from_collision,
    truncate_digest,
)

__all__ = [
    "DLPHash",
    "DLPHashParams",
    "FULL_PARAMS",
    "TOY_PARAMS",
    "birthday_collision_demo",
    "bytes_to_int",
    "bytes_to_zq",
    "compress_bytes",
    "compress_pair",
    "compression_collision_reduction_demo",
    "find_subgroup_generator",
    "generate_safe_prime_subgroup",
    "hash_bytes",
    "hash_hex",
    "hash_truncated",
    "int_to_bytes",
    "mod_exp",
    "mod_inv",
    "random_zq",
    "recover_alpha_from_collision",
    "truncate_digest",
]
